
 PARAMETER VERSION = 2.2.0


BEGIN OS
 PARAMETER OS_NAME = standalone
 PARAMETER OS_VER = 6.7
 PARAMETER PROC_INSTANCE = CORTEXM3_AXI_0
 PARAMETER stdin = axi_uartlite_0
 PARAMETER stdout = axi_uartlite_0
END


BEGIN PROCESSOR
 PARAMETER DRIVER_NAME = cpu_cortexm3
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = CORTEXM3_AXI_0
 PARAMETER extra_compiler_flags = -mcpu=cortex-m3 -Wall -Wextra -g -march=armv6-m -mthumb
END


BEGIN DRIVER
 PARAMETER DRIVER_NAME = axi_adc
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = axi_adc_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = bram
 PARAMETER DRIVER_VER = 4.3
 PARAMETER HW_INSTANCE = axi_bram_data_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = bram
 PARAMETER DRIVER_VER = 4.3
 PARAMETER HW_INSTANCE = axi_bram_insn_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = axi_dac
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = axi_dac_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = gpio
 PARAMETER DRIVER_VER = 4.4
 PARAMETER HW_INSTANCE = axi_gpio_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = uartlite
 PARAMETER DRIVER_VER = 3.2
 PARAMETER HW_INSTANCE = axi_uartlite_0
END


